version: "2"
services:
  slst-db:
    networks:
      - slst
    build: ./src/db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER postgres
      - POSTGRES_PASSWORD password
      - POSTGRES_DB slst

  slst-store:
    networks:
      - slst
    build: ./src/store
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER minioadmin
      - MINIO_ROOT_PASSWORD minioadmin

  slst-api:
    networks:
      - slst
    build: ./src/apis/Ggl.Slst.Api
    ports:
      - 5079:5079

networks:
  slst:
    driver: bridge
